project:
  type: website
  output-dir: docs

website:
  title: "Mutahir Sultan"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: CV.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false